name: biomni_e1
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  # Core Packages
  - python=3.11
  - numpy=2.1
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  
  # LangChain Suite
  - langchain
  - langgraph=0.3.18
  - langchain-openai
  - langchain-anthropic
  - langchain-ollama
  - langchain-community
  
  # AI & NLP
  - openai
  - transformers
  - sentencepiece
  
  # Web & Data Handling
  - beautifulsoup4
  - lxml
  - requests
  - pyyaml
  
  # Development & Notebooks
  - jupyter
  - notebook
  - ipykernel
  - pytest
  - tqdm
  - python-dotenv
  - networkx
  - gradio

  # Pip section for packages not on Conda
  - pip
  - pip:
    - mcp
    - tooluniverse