name: biomni_e1
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.11
  - pip
  - numpy==2.1
  - pip:
      - pandas
      - matplotlib
      - scipy
      - statsmodels
      - scikit-learn
      - gradio
      - langchain
      - langgraph==0.3.18
      - langchain-openai
      - langchain-anthropic
      - langchain-ollama
      - langchain-community
      - openai
      - beautifulsoup4
      - lxml
      - tqdm
      - seaborn
      - networkx
      - requests
      - pyyaml
      - jupyter
      - notebook
      - ipykernel
      - pytest
      - transformers
      - sentencepiece
      - mcp
      - tooluniverse
      - python-dotenv
